GestaoAgropecuria/GA.Portal/Areas/Basico/ViewModels/Animal/AnimaisIndexViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GA.Portal.Areas.Basico.ViewModels.Animal
{
    public class AnimalIndexViewModel
    {
        [Key]
        public int AnimalId { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(100)]
        [DisplayName("SISBOV")]
        public Int64 Sisbov { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("RAÇA")]
        public string Raca { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("DATA ENTRADA")]
        public DateTime DtEntrada { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("PESO ENTRADA")]
        public int PesoEntrada { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("DATA ULT. PESO")]
        public DateTime DtUltimoPeso { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("ULTIMO PESO")]
        public int UltimoPeso { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("COMUNICADO")]
        public bool Comunicado { get; set; }

        [Required(ErrorMessage = "")]
        [MaxLength(200)]
        [DisplayName("STATUS")]
        public bool Status { get; set; }

        [Required(ErrorMessage = "")]
        [DisplayName("VALOR POR CABEÇA")]
        public decimal ValorCabeca { get; set; }


    }
}

GestaoAgropecuria/GA.Portal/Areas/Basico/Controllers/Animal/AnimaisController.cs
using AutoMapper;
using GA.Dominio.Interfaces.Servicos;
using GA.Portal.Areas.Basico.ViewModels.Animal;
using GA.Portal.AutoMapper;
using LumenWorks.Framework.IO.Csv;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace GA.Portal.Areas.Basico.Controllers.Animal
{

    public class AnimaisController : Controller
    {
        private readonly IAnimalService _appService;
        private readonly IMapper _mapper;

        public AnimaisController(IAnimalService repositorio)
        {
            this._appService = repositorio;
            _mapper = AutoMapperConfig.Mapper;

        }


        //GET: Animal
        public ActionResult Index()
        {
            var animalViewModel = _mapper.Map<IEnumerable<Dominio.Entidades.Animal>, IEnumerable<AnimalIndexViewModel>>(_appService.BuscaTodos());
            return View(animalViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(System.Web.HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                if (upload != null && upload.ContentLength > 0)
                {

                    if (upload.FileName.EndsWith(".csv"))
                    {
                        Stream stream = upload.InputStream;
                        
                        using (StreamReader sr = new StreamReader(stream))
                        {
                          Importar(sr);
                        }                     
                    }
                    else
                    {
                        ModelState.AddModelError("Arquivo", "Não é suportado");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("Arquivo", "Selecione um arquivo");
                }
            }
            return View();
        }

        public ActionResult ExportCsv()
        {
            string csv = _appService.BuscaPrimeiros(50).ToList().ToString();
           return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "export.csv");
        }

        private ActionResult Importar(StreamReader csvTable)
        {
                for (int i = 0; i < csvTable.ReadLine().Count(); i++)
                {
               
                    string[] item = csvTable.ReadLine().Split(';');
                    if (!item.Contains("sisbov"))
                    {
                        var animal = new Dominio.Entidades.Animal();
                        animal.Sisbov = Int64.Parse(item.GetValue(0).ToString());
                        animal.Raca = item.GetValue(1).ToString();
                        animal.DataEntrada = DateTime.Parse(item.GetValue(2).ToString());
                        animal.PesoEntrada = int.Parse(item.GetValue(3).ToString());
                        animal.DataUltimoPeso = DateTime.Parse(item.GetValue(4).ToString());
                        animal.UltimoPeso = int.Parse(item.GetValue(5).ToString());
                        animal.Comunicado = bool.Parse(item.GetValue(6).ToString());
                        animal.Status = bool.Parse(item.GetValue(7).ToString() == "ativo" ? bool.TrueString : bool.FalseString);
                        animal.ValorArroba = decimal.Parse(item.GetValue(8).ToString());

                        var existe = _appService.BuscarSisbov(animal.Sisbov);

                        if (existe.ToList().Count == 0)
                        {
                            _appService.Incluir(animal);
                        }
                    }
               
            }

           
            var animalViewModel = _mapper.Map<IEnumerable<Dominio.Entidades.Animal>, IEnumerable<AnimalIndexViewModel>>(_appService.BuscaTodos());
                return View(animalViewModel);
         }

    }
}

GestaoAgropecuria/GA.Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GA.Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

       
    }
}

GestaoAgropecuria/GA.Portal/Areas/Basico/Views/Animais/Index.cshtml
@model IEnumerable<GA.Portal.Areas.Basico.ViewModels.Animal.AnimalIndexViewModel>

@{
    ViewBag.Title = "Listagem de animais";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Listagem de animais
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <button type="button" class="btn btn-success" href="#article-editor"data-toggle="modal" data-target="#uploadModal">Importar CSV</button> &nbsp;&nbsp;
                    <button type="button" class="btn btn-success" href="#article-editor"data-toggle="modal" data-target="#ExportCsv">
                        Exportar para CSV
                    </button>
                    <p />
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Sisbov)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Raca)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DtEntrada)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PesoEntrada)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DtUltimoPeso)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.UltimoPeso)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Comunicado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Status)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ValorCabeca)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sisbov)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Raca)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DtEntrada)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PesoEntrada)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DtUltimoPeso)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UltimoPeso)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Comunicado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ValorCabeca)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->

        </div>
        <!-- /.panel-body -->
        <div id='myModal' class='modal'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id='myModalContent'></div>
                </div>
            </div>

        </div>

    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->

<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Upload Arquivos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Upload", "Animais", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()

                    <div class="form-group">
                        <h2>Selecionar o Arquivo</h2>
                        <input type="file" id="dataFile" name="upload" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Upload" class="btn btn-default" />
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

GestaoAgropecuria/GA.Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Gestão Agropecuária";
}

<div class="row">
    <div class="col-md-4">
        <h2>Acesse o link abaixo para validar o teste</h2>
      
            @*<span class="btn-default">@Html.ActionLink("Gestão Agropecuária", "Index", "Basico/Animal/Animais")</span>*@
            @Html.ActionLink("Teste", "Index", "Basico/Animal/Animais", "Animal_default", new { @class = "navbar-brand" })
      
    </div>
</div>

GestaoAgropecuria/GA.Portal/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<div id="footer">
    <div class="container">
        
        <div class="row">
            <p>&copy; @DateTime.Now.Year </center></p>
            <p>Desenvolvedor Émerson Schulze </center></p>
        </div>
    </div>
</div>
</html>

GestaoAgropecuria/GA.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Gestão Agropecuária</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>
    <script src="~/Scripts/globalize/globalize.js"></script>
    <script src="~/Scripts/globalize/cultures/globalize.culture.pt-BR.js"></script>

    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>
</head>
<body>

    <div id="wrapper">

        @Html.ActionLink("Início", "Index", "Home", null, new { @class = "navbar-brand" })

        <div id="page-wrapper">


            @RenderBody()
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    @Html.Partial("_Footer")
                </div>
            </div>
        </footer>
    </div>

    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script>

    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>
    <!-- Custom Theme JavaScript -->

    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true,
                "language": {
                    //"url": "bower_components/datatables-plugins/i18n/Portuguese-Brasil.lang"
                    "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
                }
            });
        });


        $.validator.methods.number = function (value, element) {
            var val = Globalize.parseFloat(value);
            return this.optional(element) ||
                (val);
        }

        $.validator.methods.date = function (value, element) {
            var val = Globalize.parseDate(value);
            return this.optional(element) ||
                (val);
        }

        $(function () {

            Globalize.culture('pt-BR');

            jQuery.extend(jQuery.validator.methods, {
                range: function (value, element, param) {
                    //Use the Globalization plugin to parse the value
                    var val = Globalize.parseFloat(value);
                    return this.optional(element) || (
                        val >= param[0] && val <= param[1]);
                }
            });

        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>